AtividadeCRUDCsharp/Models/ErrorViewModel.cs
namespace AtividadeCRUDCsharp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AtividadeCRUDCsharp/Models/MunicipeModel.cs
using System.ComponentModel.DataAnnotations;

namespace AtividadeCRUDCsharp.Models
{
    public class MunicipeModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe seu nome")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "Informe seu endereço")]
        public string? Endereco { get; set; }

        [Required(ErrorMessage = "Informe seu telefone")]
        public string? Telefone { get; set; }

        [Required(ErrorMessage = "Informe seu email")]
        public string? Email { get; set; }

    }
}

AtividadeCRUDCsharp/Controllers/HomeController.cs
using AtividadeCRUDCsharp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AtividadeCRUDCsharp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AtividadeCRUDCsharp/Controllers/MunicipeController.cs
using AtividadeCRUDCsharp.Data;
using AtividadeCRUDCsharp.Models;
using Microsoft.AspNetCore.Mvc;

namespace AtividadeCRUDCsharp.Controllers
{
	public class MunicipeController : Controller
	{
		readonly private ApplicationDbContext _db;

		public MunicipeController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			IEnumerable<MunicipeModel> municipe = _db.Municipe;
			return View(municipe);
		}

		public IActionResult Cadastrar()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Cadastrar (MunicipeModel municipe) 
		{ 
			if (ModelState.IsValid)
			{
				_db.Municipe.Add(municipe);
				_db.SaveChanges();

				return RedirectToAction("Index");
			}

			return View();
		}

		[HttpGet]
		public IActionResult Editar (int? id)
		{
			if (id == null || id == 0) 
			{ 
				return NotFound();
			}

			MunicipeModel municipe = _db.Municipe.FirstOrDefault(x => x.Id == id);

			if (municipe == null)
			{
				return NotFound();
			}

			return View(municipe);
		}

		[HttpPost]
		public IActionResult Editar (MunicipeModel municipe)
		{
			if (ModelState.IsValid)
			{
				_db.Municipe.Update(municipe);
				_db.SaveChanges();

				return RedirectToAction("Index");
			}
			return View(municipe);
		}

		[HttpGet]
		public IActionResult Excluir(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			MunicipeModel municipe = _db.Municipe.FirstOrDefault(x => x.Id == id);

			if (municipe == null)
			{
				return NotFound();
			}

			return View(municipe);
		}

		[HttpPost]
		public IActionResult Excluir(MunicipeModel municipe)
		{
			if (municipe == null)
			{
				return NotFound();
			}

			_db.Municipe.Remove(municipe);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

AtividadeCRUDCsharp/Views/Municipe/Cadastrar.cshtml
@model MunicipeModel
@{
	ViewData["title"] = "Cadastro Municipe";
}

<div class="container bg-dark p-5 rounded-5">
	<div class="mb-5 text-center">
		<h1 class="text-light">Cadastro de Munícipe</h1>
	</div>

	<form method="post" asp-controller="Municipe" asp-action="Cadastrar">
		<div class="form-group">
			<label for="Nome" class="text-light">Nome</label>
			<input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Informe seu nome" />
			<span class="text-danger" asp-validation-for="Nome"></span>
		</div>
		<div class="form-group">
			<label for="Endereco" class="text-light">Endereço</label>
			<input type="text" class="form-control" asp-for="Endereco" id="Endereco" placeholder="Informe seu endereço" />
			<span class="text-danger" asp-validation-for="Endereco"></span>
		</div>
		<div class="form-group">
			<label for="Telefone" class="text-light">Telefone</label>
			<input type="text" class="form-control" asp-for="Telefone" id="Telefone" placeholder="Informe seu telefone" />
			<span class="text-danger" asp-validation-for="Telefone"></span>
		</div>
		<div class="form-group">
			<label for="Email" class="text-light">Email</label>
			<input type="text" class="form-control" asp-for="Email" id="Email" placeholder="Informe seu email" />
			<span class="text-danger" asp-validation-for="Email"></span>
		</div>
		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Enviar</button>
			<a class="btn btn-primary w-50" asp-controller="Municipe" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

AtividadeCRUDCsharp/Views/Municipe/Editar.cshtml
@model MunicipeModel
@{
	ViewData["title"] = "Editar Municipe";
}

<div class="container bg-dark p-5 rounded-5">

	<div class="mb-5 text-center">
		<h1 class="text-light">Editar Munícipe</h1>
	</div>

	<form method="post" asp-controller="Municipe" asp-action="Editar">
		<input type="hidden" asp-for="Id" />
		<div class="form-group">
			<label for="Municipe" class="text-light">Nome</label>
			<input type="text" class="form-control" asp-for="Nome" id="Nome" aria-describedby="nome" placeholder="Informe seu nome" />
			<span class="text-danger" asp-validation-for="Nome"></span>
		</div>
		<div class="form-group">
			<label for="Fornecedor" class="text-light">Endereço</label>
			<input type="text" class="form-control" asp-for="Endereco" id="Endereco" aria-describedby="endereco" placeholder="Informe seu endereço" />
			<span class="text-danger" asp-validation-for="Endereco"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Telefone</label>
			<input type="text" class="form-control" asp-for="Telefone" id="Telefone" placeholder="Informe seu telefone" />
			<span class="text-danger" asp-validation-for="Telefone"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Email</label>
			<input type="text" class="form-control" asp-for="Email" id="Email" placeholder="Informe seu email" />
			<span class="text-danger" asp-validation-for="Email"></span>
		</div>
		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Enviar</button>
			<a class="btn btn-primary w-50" asp-controller="Municipe" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

AtividadeCRUDCsharp/Views/Municipe/Excluir.cshtml
@model MunicipeModel
@{
	ViewData["title"] = "Excluir Municipe";
}

<div class="container bg-dark p-5 rounded-5">

	<div class="mb-5 text-center">
		<h1 class="text-light">Excluir Munícipe</h1>
	</div>

	<form method="post" asp-controller="Municipe" asp-action="Excluir">
		<input type="hidden" asp-for="Id" />
		<div class="form-group">
			<label for="Municipe" class="text-light">Nome</label>
			<input type="text" class="form-control" asp-for="Nome" disabled id="Nome" aria-describedby="nome" placeholder="Informe seu nome" />
			<span class="text-danger" asp-validation-for="Nome"></span>
		</div>
		<div class="form-group">
			<label for="Fornecedor" class="text-light">Endereço</label>
			<input type="text" class="form-control" asp-for="Endereco" disabled id="Endereco" aria-describedby="endereco" placeholder="Informe seu endereço" />
			<span class="text-danger" asp-validation-for="Endereco"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Telefone</label>
			<input type="text" class="form-control" asp-for="Telefone" disabled id="Telefone" placeholder="Informe seu telefone" />
			<span class="text-danger" asp-validation-for="Telefone"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Email</label>
			<input type="text" class="form-control" asp-for="Email" disabled id="Email" placeholder="Informe seu email" />
			<span class="text-danger" asp-validation-for="Email"></span>
		</div>
		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Enviar</button>
			<a class="btn btn-primary w-50" asp-controller="Municipe" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

AtividadeCRUDCsharp/Views/Municipe/Index.cshtml
@model IEnumerable<MunicipeModel>

<div class="container">
	<div class="d-flex justify-content-between align-items-center mb-5">
		<h1>Municipes</h1>
		<a class="btn btn-success mx-2" asp-controller="Municipe" asp-action="Cadastrar">Cadastrar novo municipe</a>
	</div>


	<table class="table table-stripped table-dark">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Nome</th>
				<th scope="col">Endereco</th>
				<th scope="col">Telefone</th>
				<th scope="col">Email</th>
				<th scope="col">Ações</th>
			</tr>
		</thead>
		<tbody>
			@if (Model != null)
			{
				@foreach (var municipe in Model)
				{
					<tr>
						<th scope="row">@municipe.Id</th>
						<td>@municipe.Nome</td>
						<td>@municipe.Endereco</td>
						<td>@municipe.Telefone</td>
						<td>@municipe.Email</td>
						<td>
							<a asp-controller="Municipe" asp-action="Editar" asp-route-id="@municipe.Id" class="btn btn-warning mx-2">Editar</a>
							<a asp-controller="Municipe" asp-action="Excluir" asp-route-id="@municipe.Id" class="btn btn-danger mx-2">Excluir</a>
						</td>
					</tr>
				}
			}
			else
			{
				<tr><td><strong>Nenhum Municipe foi realizado!</strong></td></tr>
			}
		</tbody>
	</table>
</div>

@{

}

AtividadeCRUDCsharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtividadeCRUDCsharp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AtividadeCRUDCsharp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AtividadeCRUDCsharp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Municipe" asp-action="Index">Municipe</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AtividadeCRUDCsharp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>